.coefficient_indices_for_terms <- function(model_terms, X, requested, offset) {
  labels <- attr(model_terms, "term.labels")
  missing <- setdiff(requested, labels)
  if (length(missing)) {
    stop("Terms not present in both submodels: ", paste(missing, collapse = ", "), call. = FALSE)
  }
  assign <- attr(X, "assign")
  term_numbers <- match(requested, labels)
  offset + which(assign %in% term_numbers)
}

.drop_formula_terms <- function(formula, requested) {
  trm <- stats::terms(formula)
  retained <- setdiff(attr(trm, "term.labels"), requested)
  response <- paste(deparse(formula[[2L]]), collapse = "")
  stats::reformulate(retained, response = response, intercept = attr(trm, "intercept") == 1L)
}

#' Omnibus test of terms shared by both submodels
#'
#' Tests that every coefficient generated by the requested formula terms is
#' zero in both submodels. Factors therefore contribute all their non-reference
#' coefficients. The Wald test uses the full covariance matrix, including
#' cross-submodel covariance. The likelihood-ratio test removes the terms from
#' both formulas and refits the model.
#'
#' @param object A fitted `joint_bc` object.
#' @param terms Character vector of exact formula term labels shared by both
#'   submodels, for example `"treatment"`.
#' @param method `"wald"`, `"lrt"`, or `"both"`.
#' @return A data frame containing the requested test(s).
#' @export
joint_test <- function(object, terms, method = c("wald", "lrt", "both")) {
  if (!inherits(object, "joint_bc")) stop("`object` must be a `joint_bc` fit.", call. = FALSE)
  method <- match.arg(method)
  if (!is.character(terms) || !length(terms) || anyNA(terms)) {
    stop("`terms` must be a non-empty character vector.", call. = FALSE)
  }
  terms <- unique(terms)
  p_c <- ncol(object$X_continuous)
  idx_c <- .coefficient_indices_for_terms(
    object$terms_continuous, object$X_continuous, terms, 0L
  )
  idx_b <- .coefficient_indices_for_terms(
    object$terms_binary, object$X_binary, terms, p_c
  )
  idx <- c(idx_c, idx_b)

  rows <- list()
  if (method %in% c("wald", "both")) {
    b <- object$coefficients[idx]
    V <- object$vcov[idx, idx, drop = FALSE]
    statistic <- drop(crossprod(b, solve(V, b)))
    rows[[length(rows) + 1L]] <- data.frame(
      method = "Wald", statistic = statistic, df = length(idx),
      p_value = stats::pchisq(statistic, df = length(idx), lower.tail = FALSE)
    )
  }

  if (method %in% c("lrt", "both")) {
    if (is.null(object$data)) {
      stop("The LRT requires a model fitted with `keep_data = TRUE`.", call. = FALSE)
    }
    reduced_c <- .drop_formula_terms(object$formula_continuous, terms)
    reduced_b <- .drop_formula_terms(object$formula_binary, terms)
    reduced <- joint_bc(
      reduced_c, reduced_b, data = object$data, link = object$link,
      n_quad = object$n_quad, control = object$control, keep_data = FALSE
    )
    if (reduced$convergence != 0L) warning("The reduced model did not report successful convergence.", call. = FALSE)
    statistic <- max(0, 2 * (object$logLik - reduced$logLik))
    df <- length(object$coefficients) - length(reduced$coefficients)
    rows[[length(rows) + 1L]] <- data.frame(
      method = "Likelihood ratio", statistic = statistic, df = df,
      p_value = stats::pchisq(statistic, df = df, lower.tail = FALSE)
    )
    attr(rows[[length(rows)]], "reduced_model") <- reduced
  }
  result <- do.call(rbind, rows)
  row.names(result) <- NULL
  attr(result, "terms") <- terms
  result
}

